### ISSUE TITLE
New Category is not creating with API V3

### ISSUE THREAD

**Issue by pankajk79** [bigcommerce/api#100]
I can create Product using API V3. But when I attempt to create "categories" I got response "403 Authentication Required".

Please guide me what steps required so I can create categories, brands, option, option-values using API V3. I have selected all scopes to "modify" while creating "API Account from BC Admin section  "Advanced Settings.--> API Accounts"

Thanks.

**Comment by zvuki** [comment]
Hi @pankajk79, `Products` scope gives you access to categories, brands, option, option-values.

Most likely you've had a trailing stash `categories/` when you made a request, could you make sure that you don't have it?

**Comment by pankajk79** [comment]
Hi @zvuki, thanks your prediction was correct, I have removed trailing slash and it is working. Thanks a lot.
