### ISSUE TITLE
Can't update `inventory_tracking` for product

### ISSUE THREAD

**Issue by RichardHeelin** [bigcommerce/api#22]
According to the docs, you can set the products `inventory_tracking` to change how stock is managed.

> The type of inventory tracking for the product: One of: none - inventory levels will not be tracked; product - inventory levels will be tracked using the inventory_level and inventory_warning_level fields; or variant - inventory levels will be tracked based on variants, which maintain their own warning levels and inventory levels.

However, any attempt to update it results in a 422 Unprocessable Entity.

```
{"id":80,"inventory_tracking":"variant"}
```

```
{"status":422,"title":"Invalid field(s): inventory_tracking","type":"https://developer.bigcommerce.com/api/status-codes","errors";:{"inventory_tracking":"inventory_tracking must be equals \"none\""}}
```

**Comment by RichardHeelin** [comment]
It seems that the v3 api values, `product` and `variant` are not yet supported! However you can use their v2 equivalents:
    `product` => `simple`
    `variant` => 'sku'

**Comment by ICarpenter** [comment]
@RichardHeelin Good point here. The values in the enum should reflect our current naming scheme. The concern is compatibly between versions of the API. The goal is to be as close as possible to make the transition to v3 as painless as possible.
