### ISSUE TITLE
Webhooks - Category Create/Update/Delete

### ISSUE THREAD

**Issue by kenmau** [bigcommerce/api#29]
Would love to see the addition of supporting Category resource webhooks!  "Categories" are already one huge advantage BigCommerce has over Shopify, and would love to see more support for this in the developer community.

**Comment by bc-AlyssNoland** [comment]
@kenmau Would love to get more of your thoughts on how you would use these categories so we can build the developer story :)

**Comment by kenmau** [comment]
@bc-AlyssNoland Thanks for reaching out and listening to the feedback from us developers!

We absolutely love the that our native iOS mobile apps can integrate so deeply with the BigCommerce ecosystem to help merchants take their shop omni-channel with their customers.

With product webhooks, Merchants love how when they update their product attributes (like name, pricing, etc), these changes immediately get propagated to our shopping apps.  Or, when an order status gets updated, our shopping app can notify customers in real time of any changes.

Much similarly with Product Categories, our merchants are consistently expanding their stores and offering more products and more variety, our apps would very much benefit from their growing success if we can keep up to date with their categories.

We work quite intimately with BigCommerce APIs and would be very happy to provide any additional feedback!

Thanks, Alyss!

**Comment by bc-AlyssNoland** [comment]
@kenmau I have great news. It turns out we have these webhooks, but they hadn't been documented yet. I've sent the documentation request to our tech writer. 

In the meantime: 
**New webhook events**
_store/category/*_
_store/category/created_
_store/category/updated_
_store/category/deleted_

**Comment by kenmau** [comment]
Wow, thanks @bc-AlyssNoland !  We'll give this a try.
