### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by qiun** [bigcommerce/api#32]
For most of the shops that we download product data for, the api returns this error: 504 Gateway Timeout. This has been happening for approx 36 hours. Downlaoding the data again only results in the same error. the 504 indicates that 
We are DataFeedWatch (www.DataFeedWatch.com) and a few examples of shops that are returning this error are http://matchpoint-tennis.com or http://www.wakehouse.com

Has anyone experienced the same problem? Will BigCommerce investigate?

**Comment by aleachjr** [comment]
@qiun we are looking into this issue, will update as we have more information.

**Comment by chrisboulton** [comment]
Hey @qiun,

Can you confirm for me if this is resolved now? It looks like we had a bit of misbehaving infrastructure that was affecting some API calls. We've restarted it, and it seems to be playing nicer now. I'll be working with our team to correct the monitoring gap here.

**Comment by qiun** [comment]
Still we have the same problem for shops are on API we get error: 504 Gateway Timeout.

**Comment by tooloha** [comment]
Any update on this issue? We have a bunch of very unhappy customers who have not been able to update their products on Google, Amazon or any of the other shopping channels. Fixing this will make them (and us) very happy ...

**Comment by chrisboulton** [comment]
Thanks for the heads up - sorry this is still causing problems. We've pulled the affected infrastructure entirely and are working on diagnosing why it's not working correctly. Can you confirm for us now if you're still experiencing 504s?

**Comment by tooloha** [comment]
the problem is solved. thanks. If this will happen again, is this page the right place to report?

**Comment by chrisboulton** [comment]
Thanks for the update!

>  If this will happen again, is this page the right place to report?

I'm hoping we know about it before you - I've got to catch up with our teams tomorrow to get this gap covered and any others identified and covered.

I'd say this repo is one option - I can say I'm personally subscribed to be notified of issues created here, but our broader teams probably aren't. The best place would be via our support services (live chat, ticket, phone call, or even a partner manager), as those will typically get you in front of the right people, quicker.

Thanks again for the report, and understand we'll be working to ensure this issue doesn't come up again in the future. It's equally as frustrating and business impacting for us as it is you.
