### ISSUE TITLE
Creating new Customer from API does not respect Customer Group setting

### ISSUE THREAD

**Issue by kenmau** [bigcommerce/api#38]
Hi BigC,

When creating a new customer via the API, it doesn't respect the setting in Customer Groups: "All new customers should be added to this group".

![image](https://cloud.githubusercontent.com/assets/4250685/20760764/da3331d8-b6ee-11e6-9db5-da8a64340736.png)

![pasted_image_2016-11-30__11_20_am](https://cloud.githubusercontent.com/assets/4250685/20760876/2d6d62d8-b6ef-11e6-939e-cddb283d840c.png)

Thanks!

**Comment by bc-AlyssNoland** [comment]
We are looking at resolving this in a V3 iteration. Sign up for our developer newsletter or keep an eye on the [changelog](developer.bigcommerce.com/changelog).

**Comment by bc-AlyssNoland** [comment]
@kenmau We're looking at implementing a fix for this, but it will go through a slow rollout to ensure we aren't breaking existing integrations that expect this behavior.

**Comment by bookernath** [comment]
Fixed.
