### ISSUE TITLE
API v2 legacy swagger

### ISSUE THREAD

**Issue by Lewiscowles1986** [bigcommerce/api#39]
It would be really nice to have v2 documented as part of this also as it's still live and very much a part of BigCommerce whilst v3 is being worked out & implemented

**Comment by bc-AlyssNoland** [comment]
developer.bigcommerce.com has all the V2 documentation up and live. We have considered what work would be required to be able to generate swagger for our V2 endpoints, but the original implementation of them didn't take this desire into consideration (as Swagger didn't start development until 2010 and this code was worked on in 2008 or earlier). 

Is there something you are looking for in particular?

**Comment by Lewiscowles1986** [comment]
I'd like to be able to track that functionality is not lost, and having a few .yml files to merge would make that a very visual process for me. It would also help to generate mock servers for testing.

**Comment by bc-AlyssNoland** [comment]
We don't currently have it as the way we are building APIs now is different than how we built in the past. We'll definitely keep this in mind, but I can't make any promises about being able to complete work on these.

**Comment by Lewiscowles1986** [comment]
I certainly wouldn't want you working on it on a Sunday, but thanks for the update :+1: :wink:

**Comment by bc-AlyssNoland** [comment]
I'm going to close this issue for now, but I'll be sure to include an update in our changelog or in a developer newsletter update if decide to create and provide these.
