### ISSUE TITLE
US states being returned as abbreviations

### ISSUE THREAD

**Issue by dstaley** [bigcommerce/api#40]
The `state` field in an address response from the API has the following note in the documentation:

> The name of the state. Should be spelled out in full, e.g.: `California`.

This morning we received an order where the `state` field was `CY`. The first issue is that it's not conforming to the documentation, and the second issue is that `CY` isn't a valid abbreviation for a US state. The ZIP code the customer provided is a Connecticut address, so the abbreviation should have been `CT`. I think this is because the customer used Apple Pay, which I guess doesn't do any sort of address validation?

Also looking back through all our previous orders, we've had 30 instances where the `state` field was an abbreviation instead of the fully spelled out state name.

**Comment by bc-AlyssNoland** [comment]
@dstaley Are you still seeing this?

**Comment by dstaley** [comment]
@bc-AlyssNoland the most recent occurrence I see is from December 15. I have 29 US orders where the billing state is being returned as an abbreviation. The majority are correct state abbreviations though.

**Comment by bc-AlyssNoland** [comment]
@dstaley cool. I am going to close this for the time being, but if you see the behavior come up again, please reopen.
