### ISSUE TITLE
Getting Option Set Rules via API

### ISSUE THREAD

**Issue by kenmau** [bigcommerce/api#41]
Hi BigC Team!

It's been raised many times before, but I just wanted to state for record that without the ability to retrieve Option Set Rules, the ability to retrieve Products, Product Rules, Product Options, etc. is NOT complete as Option Set Rules have a direct impact to Product pricing and/or weight.

http://stackoverflow.com/questions/20283454/how-to-get-option-set-rules-in-bigcommerce
http://stackoverflow.com/questions/23506023/get-option-set-rules-from-bigcommerec-api
http://stackoverflow.com/questions/24820775/option-set-rules-not-comming-from-bigcommerce-api

Can you let me know if there is currently a way, or is this planned for support?

Thanks!

**Comment by bc-AlyssNoland** [comment]
@kenmau It is possible to retrieve product modifiers using V3. Does this address your concern?

**Comment by bookernath** [comment]
Hi @kenmau,

In our V3 API, option sets (and by extension, Option Set Rules) are actually deprecated - our CP UI will be updated to better reflect this over time as we sort out the migration of existing merchants to our new model.

However, the V3 API also provides a `calculated_price` property for any variants in the catalog which will take into account all of the complexity in the system to provide you with the appropriate variant pricing - it will automatically factor in variant pricing, product rules, option set rules, sale price, etc. I'd suggest taking a look at that to see if it works for you!
