### ISSUE TITLE
v3: /catalog/variants returns variants with no associated products

### ISSUE THREAD

**Issue by kfreytag** [bigcommerce/api#44]
Requesting all variants for a store that has been around for some time results in some variants that have a ```product_id``` of ```0```.

For this particular store, there are 21,969 total results from ```/catalog/variants```. 9,188 of them have a ```product_id``` of ```0``` and 12,781 of them have a non-zero ```product_id``` that does exist in the ```/catalog/products``` endpoint.

Pulling the variants through the ```/catalog/products``` endpoint using ```?include=variants``` query parameter, however, returns only the 12,781 variants that are actually associated with products.

Desired behavior: the ```/catalog/variants``` endpoint should return the same records that are returned when using the ```?include=variants``` query parameter on the ```/catalog/products``` endpoint. Returning orphaned variants is confusing, as these variants cannot appear on a store and cannot be found through the administrative interface.

Note : There is certainly value to being able to retrieve previously-deleted products and variants, but that functionality should be optional.

**Comment by bc-sandeep** [comment]
Hi @kfreytag Can you send your store details( just store id will do) please once to diagnoze this?

Also, Do you actually see variant rows with product_id =0 in the response or are you going off  with `total` in meta-->pagination part of response . 
I can see total counting orphan variants to, while `count` is returning count of non orphan skus from some local testing

**Comment by kfreytag** [comment]
@bc-sandeep Apologies for the delayed response. For some reason, GitHub didn't notify me of your comment, and I just stumbled across it.

I do actually see variant rows with `product_id` == `0` in the response.

As of right now, the v3 `/catalog/variants` endpoint is returning 19,716 Variants for store `ox79uhj`. 9,172 of those have a `product_id` of `0`.

**Comment by bc-sandeep** [comment]
yeah, the store has some orphan sku's from legacy i believe.
