### ISSUE TITLE
Will v3 have access to the same resources as v2?

### ISSUE THREAD

**Issue by tnagle** [bigcommerce/api#55]
I was playing around with converting my app from v2 to v3 and tried to grab the tax classes.

V2 works fine, as usual:
https://api.bigcommerce.com/stores/myhash/v2/tax_classes

But attempting the same with v3 (https://api.bigcommerce.com/stores/myhash/v3/tax_classes) returns...

"You are authorized but your scope does not include this resource."

...even though I gave the credentials modify on all OAuth scopes. On reviewing the docs I see that, tax classes are not yet present in the API (other than fetching the tax class ID when getting a product).

Will v3 eventually have access to all non-deprecated v2 resources?

Thanks!
-Tom

**Comment by bc-AlyssNoland** [comment]
There is currently no V3 tax endpoint. We are iteratively releasing endpoints as we have them available. If you want to stay in the loop, we will make announcements via our developer newsletter and on the developer [changelog](developer.bigcommerce.com/changelog). 

Currently, V3 has a catalog endpoint and a customer newsletter subscriber endpoint.
