### ISSUE TITLE
Product variants option_values not updating

### ISSUE THREAD

**Issue by dhavaloo** [bigcommerce/api#56]
- /catalog/products/{product_id}/variants/{variant_id}
Example
```
{
          "id": 90,
          "product_id": 116,
          "sku": "sku-denim-jeans-blue-32",
          "price": 99.99,
          "inventory_level": 0,
          "inventory_warning_level": 0,
          "option_values": [
            {
              "id": 109,
              "label": "Blue",
              "option_id": 120,
              "option_display_name": "Color"
            },
            {
              "id": 108,
              "label": "32",
              "option_id": 121,
              "option_display_name": "Size"
            },
            {
              "id": 111,
              "label": "Green",
              "option_id": 122,
              "option_display_name": "Fabrics"
            }
          ]
        }
```
I want to change last option value, from Green(111) to White(110), but it is not working.
There will be no error even, response was 200 OK, with same old option_values

**Comment by bc-AlyssNoland** [comment]
@dhavaloo can you post the code or request content [stackoverflow](https://stackoverflow.com/questions/tagged/bigcommerce) or our [developer forums](https://forum.bigcommerce.com/s/group/0F913000000HLjECAW)?

**Comment by ICarpenter** [comment]
@dhavaloo currently you cannot update the option_values for a variant. There are no current plans to support this. Please delete the variant and recreate it with the appropriate option_values. To give you some background, by allowing the editing of option_values we are allowing for more vectors by which a product's variants can get out of sync with the options on a product. I apologize for the inconvenience.

**Comment by ICarpenter** [comment]
Closed as an "undocumented feature".
