### ISSUE TITLE
No way to create coupon codes?

### ISSUE THREAD

**Issue by danwaltzer** [bigcommerce/api#57]
Through Shopify and other e-commerce platforms, the ability to create coupon codes is available through the API. Is this functionality not available with the Bigcommerce API?

**Comment by bc-AlyssNoland** [comment]
Hey @danwaltzer

The documentation for the V2 endpoint to create coupons is documented here: https://developer.bigcommerce.com/api/v2/#create-a-coupon

**Comment by danwaltzer** [comment]
@bc-AlyssNoland Perfect thank you!
