### ISSUE TITLE
Variant option values labels are broken

### ISSUE THREAD

**Issue by humphrey** [bigcommerce/api#58]
Bothe endpoints `/catalog/products` and `/catalog/products/0000` show invalid option label when the option label has a comma (`,`) in the label.

Eg... on the website the options show like this:

![screen shot 2017-03-01 at 4 41 10 pm](https://cloud.githubusercontent.com/assets/229874/23447330/3b8b6d50-fe9e-11e6-8a59-5f6409b228aa.png)

But in the API, the options show like this:

![screen shot 2017-03-01 at 4 39 57 pm](https://cloud.githubusercontent.com/assets/229874/23447389/96703d5e-fe9e-11e6-854e-f004dd9f9bd7.png)

It appears that it's splitting on a comma, and putting what's after the comma in option 2, as the label for option 3. And it's completely missed out the text for option three.

I'm assuming I can get around this by calling `/catalog/products/0000/options` -- but that will mean I have to do 10,000 api calls instead of about 50.

**Comment by ICarpenter** [comment]
@humphrey thank you for pointing this out! @bpasieka has created a fix that will be making its way into production in the next few days.
