### ISSUE TITLE
Store Product Count

### ISSUE THREAD

**Issue by jlee2027** [bigcommerce/api#59]
It seems the old V2 Call:
https://api.bigcommerce.com/"store_hash"/v2/products/count

Isn't working at the moment. I opened a thread on the Developer Forum about this earlier today.  So I just tried v3 to get a product count.

I don't see a method to get a count of how many products are in a store. We need this. Please advise, thanks

**Comment by jlee2027** [comment]
Well, V2 and V3 were not working until about midnight last night (returning NULL on calls) and then both started working very well w/o us making any changes. WE are on the East Coast, perhaps this was a local issue?  I don't know. 

However, I did find a product count in V3 attached to each product read. That will work nicely....

I'm going to close this issue, thank you.  What is the rollout date for V3?

**Comment by bc-AlyssNoland** [comment]
@jlee2027 V3 is available and rolled out. We are continuously working to add new endpoints.

**Comment by elliot-hagerty** [comment]
Did you find a way to do this on V3? I can't seem to find the method.

**Comment by ralucanl** [comment]
try   https://api.bigcommerce.com/stores/store_hash/v3/catalog/summary
