### ISSUE TITLE
Cart API questions

### ISSUE THREAD

**Issue by remarkety** [bigcommerce/api#6]
Hi team,
Great work, looking forward to start using it.
Few questions:
1. We need to be able to get ALL checkouts of a store, in a single call. Would it be possible? Without this option the API is practically useless to us, since we are syncing the carts on behalf of many stores.
2. In the draft, I didn't see the product ID in the lineItem properties.

Thank you,
Tzvi

**Comment by brandonkane** [comment]
Yes for #1 we'll need list endpoints that also allow filtering by created/modified dates, status, etc.

**Comment by serroba** [comment]
Hey @remarkety thanks for your questions!

* 1. I am not sure if we will be able to retrieve them _all_ but the idea of this new endpoint is that you will be able to retrieve collections with sort and page enabled. We may need to set a limit in the page size for technical reasons, but on of the ideas is to enable access to collections.
* 2. As @brandonkane mention, in under `variant`. More about this will soon be explained with more details.

**Comment by carsonreinke** [comment]
@serroba If not collection to access all current checkouts, at least webhook notifications of creation and modification.

**Comment by brandonkane** [comment]
If this is API is going to be a first class citizen in the BigCommerce world it should have both collection access to all checkouts (with filtering, paging and sensible limits on page sizes) as well as full webhook support.

**Comment by aleachjr** [comment]
I fully agree that we need to ensure that we have Webhooks for this. We have spent time over the last 6 months beefing up our Webhooks integration and should have no issue supporting this new model once we have APIs to back it.
