### ISSUE TITLE
V2: Update a Customer form_fields property

### ISSUE THREAD

**Issue by enjoyjeremy** [bigcommerce/api#61]
I've been trying to update a customer through the V2 API and pass the form_fields property, but I'm getting an error saying `The field 'name' is invalid.`. Is the format below correct?

```
{
  "email": "customer@email.com",
  "first_name": "John",
  "last_name": "Doe",
  "company": "ACME",
  "phone": "1234567890",
  "form_fields": [
    {
      "name": "Occupation",
      "value": "Worker"
    },
    {
      "name": "Bio",
      "value": "I am a Bigcommerce customer."
    },
    {
      "name": "Profile Photo",
      "value": "http://example.com/photo.jpg"
    }
  ],
  "customer_group_id": 9
}
```

**Comment by bc-AlyssNoland** [comment]
@enjoyjeremy currently, custom form fields are not put or post-able. They are GET only. We are working on adding this in the near future

**Comment by enjoyjeremy** [comment]
Okay, good to know. This feature would help me out greatly, as I'm currently having to resort to some pretty nasty hacks as a workaround. Thanks!
