### ISSUE TITLE
Product Post with Images

### ISSUE THREAD

**Issue by jlee2027** [bigcommerce/api#67]
I can create a V3 Product with variants.  I can, separately, create and attach images. However, I can save one step according to the Docs:

Create Product:
https://github.com/bigcommerce/api/blob/master/docs/v3-catalog.md#createProduct
which references: the Product Post body:
https://github.com/bigcommerce/api/blob/master/docs/v3-catalog.md#ProductPost
I can supply an array of Images to the Product Post
**images (optional)
array[ProductImage]**

I assume this means when I create a product, I can give it an array of images to add to the Product (like with Variants/Options). However, it's not working. I can send a POST through and the Product is created, but the Image portion is ignored.

'{"name":"New Genuine Apple MD827LL/A Earpods Earphones for iPhone 6 5 4S w/Remote & Mic","type":"physical","description":"New DESC TEST","sku":"38200377626","price":"9.89","sale_price":0,"inventory_tracking":"variant","inventory_level":2400,"availability":"available","weight":2,"upc":"MPN: MD827LL/A","width":0,"height":0,"depth":0,"categories":["972","973","971"],"condition":"New","is_condition_shown":true,"is_visible":true,"images":[{"image_url":"http://i.ebayimg.com/00/s/NzA1WDExNzc=/z/BfAAAOSwhQhYyZrt/$_57.JPG"},{"image_url":"http://i.ebayimg.com/00/s/NzA5WDgwMw==/z/zhUAAOSwsW9YyZlW/$_57.JPG"},{"image_url":"http://i.ebayimg.com/00/s/NjE3WDY1NA==/z/FosAAOSwSlBYyZl3/$_57.JPG"},{"image_url":"http://i.ebayimg.com/00/s/NjYzWDY0MA==/z/H-IAAOSwYXVYyZl4/$_57.JPG"},{"image_url":"http://i.ebayimg.com/00/s/NjE3WDY1NA==/z/11cAAOSwB-1YyZti/$_57.JPG"}],"variants":[{"sku":"head/215/00","price":"9.89","inventory_level":1000,"option_values":[{"option_display_name":"Connector(s)","label":"3.5mm Jack"}]},{"sku":"head/5022/00","price":"24.29","inventory_level":1400,"option_values":[{"option_display_name":"Connector(s)","label":"Lightning"}]}]}'

The API response returns a null array for the images, but does create the product with the variants I requested. But no images are created.

Am I doing something wrong?  Thank you.

**Comment by ICarpenter** [comment]
@jlee2027 this is not currently supported on the products resource. However we are considering adding it in the near future. The documentation is not correct here due the reuse of swagger model for GET and POST. Thank you for pointing out the error in the documentation.

**Comment by ICarpenter** [comment]
@jlee2027 I just checked the docs and it appears that `images` were not mistakenly added to the POST and PUT objects. PUT responses will contain `images` if there are any images on the product.   I will update this issue when we are able to push out the feature.

**Comment by bc-jz** [comment]
I have removed `images` from the `ProductPost` and `ProductPut` descriptions for now until we can address adding that behavior.
