### ISSUE TITLE
Can't attach variants with new option values to existing products

### ISSUE THREAD

**Issue by ruianderson** [bigcommerce/api#71]
Hi, I tried to add new variants that have new option values to an existing product but I couldn't. I did the following steps:

1 - Created a product with variants and a few options values (i.e: Color: Red)
2 - Tried to add more variants with new options values to the previously created product. The options values within this new variant have the same name `display_name` with a different value (Color: Blue).

I tried two approaches:

**PUT on `products/:id` and sending on `variants` fields both new and existing variants:**

```
I, [2017-03-17T14:28:48.753992 #1]  INFO -- : put https://api.bigcommerce.com/stores/yb114lpr9d/v3/catalog/products/146
D, [2017-03-17T14:28:48.754113 #1] DEBUG -- request: accept: "application/json"
content-type: "application/json"
X-Auth-Client: "*******"
X-Auth-Token: "*******"
User-Agent: "Faraday v0.9.2"
D, [2017-03-17T14:28:48.754176 #1] DEBUG -- request: {"name":"Rui's","description":"<p>My Grid</p>","is_visible":true,"type":"physical","price":30.0,"categories":["23"],"weight":16.0,"variants":[{"product_id":146,"sku":"100070","option_values":[{"option_display_name":"Color Name (Custom Field)","label":"Blue"},{"option_display_name":"Size (Custom Field)","label":"X"}],"price":30.0,"cost_price":10.0},{"id":"203","product_id":146,"sku":"100071","option_values":[{"option_display_name":"Color Name (Custom Field)","label":"Blue"},{"option_display_name":"Size (Custom Field)","label":"S"}],"price":30.0,"cost_price":10.0},{"id":"204","product_id":146,"sku":"100072","option_values":[{"option_display_name":"Color Name (Custom Field)","label":"Red"},{"option_display_name":"Size (Custom Field)","label":"X"}],"price":30.0,"cost_price":10.0},{"id":"205","product_id":146,"sku":"100073","option_values":[{"option_display_name":"Color Name (Custom Field)","label":"Red"},{"option_display_name":"Size (Custom Field)","label":"S"}],"price":30.0,"cost_price":10.0}]}
I, [2017-03-17T14:28:49.939412 #1]  INFO -- Status: 422
D, [2017-03-17T14:28:49.939613 #1] DEBUG -- response: server: "nginx"
date: "Fri, 17 Mar 2017 14:29:21 GMT"
content-type: "application/problem+json"
content-length: "141"
connection: "close"
vary: "Accept-Encoding"
D, [2017-03-17T14:28:49.939681 #1] DEBUG -- response: {"status":422,"title":"Missing Required Fields","type":"https://developer.bigcommerce.com/api/status-codes","errors":{"id":"Please provide a id."}}
```

**POST on `products/:id/variants` to add a single variant to the product:**

```
I, [2017-03-17T14:31:26.544437 #1]  INFO -- : post https://api.bigcommerce.com/stores/yb114lpr9d/v3/catalog/products/146/variants
D, [2017-03-17T14:31:26.544483 #1] DEBUG -- request: accept: "application/json"
content-type: "application/json"
X-Auth-Client: "*******"
X-Auth-Token: "*******"
User-Agent: "Faraday v0.9.2"
D, [2017-03-17T14:31:26.544498 #1] DEBUG -- request: {"product_id":146,"sku":"100070","option_values":[{"option_display_name":"Color Name (Custom Field)","label":"Blue"},{"option_display_name":"Size (Custom Field)","label":"X"}],"price":30.0,"cost_price":10.0}
I, [2017-03-17T14:31:27.874726 #1]  INFO -- Status: 422
D, [2017-03-17T14:31:27.874767 #1] DEBUG -- response: server: "nginx"
date: "Fri, 17 Mar 2017 14:31:59 GMT"
content-type: "application/problem+json"
content-length: "169"
connection: "close"
vary: "Accept-Encoding"
D, [2017-03-17T14:31:27.874784 #1] DEBUG -- response: {"status":422,"title":"Invalid field(s): option_values.0.id, option_values.0.option_id","type":"https://developer.bigcommerce.com/api/status-codes","errors":{"option_values.0.id":"Please provide a id.","option_values.0.option_id":"Please provide a option_id."}}
```

How should I approach this scenario? When creating the product all embedded variants and its options are created on the fly as mentioned on doc so I was expecting to attach variants and its options be created/associated as well.

It looks like I will have to do that steps in order to accomplish my goal:

- Fetch the product options
- Find the `option_id` of the option I want add the value
- Perform a PUT to update the option with the new value
- Finally perform a POST to the product to add the variant (passing the option id and option value id on `option_values` field)

**Comment by bc-jz** [comment]
Hi Rui,

You are correct in your assessment.  At this time the POST to create a product is the only time you can add variants along with their options and values in a single request.  After a product has been created you must follow the process you detailed at the end of your email:

- Find the existing product options on the product with a GET to a relative path:
`/catalog/products/ID/options`

- Use a PUT to add new values to a particular option by it's option ID, ie:
`/catalog/products/ID/options/OPTIONID`

You only need to send the `option_values` array in this case.  Note also that you can add multiple new option values in the same request as well as update existing values to have a different label (or other change) by including it's `id` in the request.

It will take additional PUT requests to update other options on the same product.

- Once you have updated your option values they will now have ID values associated with them.  At that point you can start creating your variants as you mentioned by passing the option `id` and the option value reference, `option_id`.

I hope this clarifies things and gets you going but do let us know if you have further questions on this topic.  Thank you for your feedback and efforts!

**Comment by bc-jz** [comment]
For completeness, know that you can also send `POST` requests to the `values` subresource of a particular option ID to create new values, ie, a relative path of:

`/catalog/products/ID/options/OPTIONID/values`

When doing this you can only add a single new value but the only structure you need to pass is that of a new value with it's `sort_order` number, such as:

`{"label": "new option value", "sort_order": 5}`

**Comment by bc-AlyssNoland** [comment]
Closed issue. Please reopen if necessary, but this appears to be expected behavior.

**Comment by jdcryer** [comment]
I am having a related issue.  I got all the way through the process described above to the point that I was trying to create an OptionValue as described.  However, I keep getting a message stating that value_data must be an array.  See below url for post, request and response:
https://api.bigcommerce.com/stores/xxxxxxxxxx/v3/catalog/products/1341/options/2560/values

{"label": "Black", "sort_order": 3, "value_data": {"colors": ["http://i1.adis.ws/s/brand/YM091_Black?$poiswatch$"]}}

{"status":422,"title":"Invalid field(s): value_data","type":"https://developer.bigcommerce.com/api#api-status-codes","errors":{"value_data":"value_data must be an array"}}

I have also tried the simpler label/sort_order request body you suggested but get the same result.
Am I doing something wrong or is this a bug related to swatch type options when trying to add an option value?
