### ISSUE TITLE
Product updating SKUs by SKU and inventory level

### ISSUE THREAD

**Issue by Lewiscowles1986** [bigcommerce/api#74]
So it's explicitly written that I can create a product and include variants. Is it possible to bulk update SKU inventory_level in a single call also?

Alternatively if I have an inventory_level value to set for multiple SKU's would there be an option to bulk update those? The core theme here is SET based workloads for products.

**Comment by jdcryer** [comment]
Yes you can do this with the v3 API.  The payload to the PUT v3/catalog/products/#productid call would be as below:
{
	"variants": [
		{
			"id": 10805,
			"product_id": 1341,
			"inventory_level": 2
		},
		{
			"id": 10806,
			"product_id": 1341,
			"inventory_level": 4
		}
	]
}
One call per product as opposed to one call per variant.  Some people have hundreds of variants so this is far more efficient.

**Comment by Lewiscowles1986** [comment]
I take it that is so that you can limit the payload size sent in to keep request / response times low?

I ask because we currently have a middleware for a legacy ERP that has been working with BigCommerce since 2013 & this is a pain point. The above is a step forward, but really, even if we have 4000 unique SKU's over 400 products, it would be easier to be able to say "here is a list of SKU, inventory pairs", and let the platform resolve that. 

This is quite a low-level implementation
