### ISSUE TITLE
Linked resources lead to incredibly long download times

### ISSUE THREAD

**Issue by Lewiscowles1986** [bigcommerce/api#78]
Is there any way you could see it in your hearts to add full-document API for orders, maybe products too? (basically no linked resources, a product or order from these endpoints would contain sub-documents built-in rather than requiring resource calls).

The problem is that we can bulk list orders 250 at a time, but have to get their linked products one at a time :cry: 

Recently backed up a store with >65000 orders. Our reference script is single-threaded, and not concurrent (which are other options to speed up), and it took 12 hours to complete, yielding a file that was 283.6MB (~6.5KB/s). We want to be good citizens and responsible API consumers.

If I Just get the order data and no linked resources, it takes < 20 minutes to download all the orders. Obviously constantly backing up all orders has no benefit, but it'd be nice to have it not take an order of magnitude more calls, often for tiny amounts of data

65531/250 = 263 calls (core order data)
65531 product resource calls (populating product ledger data only SKU, qty, price needed)
65531 coupon resource calls (populating coupon data)
65531 shipping addresses calls (populating shipping address data)

so going from 263 -> 196,856 calls (c'mon that's a lot!)
even if we only processed one page every time it would be from 1(just 250 orders) -> 751(250 orders + 3*250 for the three linked data areas) calls to get this data

**Comment by bc-AlyssNoland** [comment]
@Lewiscowles1986 Adding an V3 orders endpoint with similar features to our v3 catalog endpoint is on our roadmap! We definitely understand what a pain point this is, especially with one of our most utilized resources. 

I'll have someone else jump in and see if they can make any suggestions to help in the meantime.

**Comment by bc-jz** [comment]
Hi @Lewiscowles1986 - it is not well known but most subresources can be grabbed in chunks of 250 without regard to a parent resource.  Utilizing this you would just need to attach the subresource objects to their parents by the parent resource ID provided in the subresource object.  

In regards to Orders all relevant subresources allow this.  For example, you can make a GET request to these relative paths to retrieve up to 250 subresource objects:

`/v2/orders/products?limit=250&page=1`
`/v2/orders/shippingaddresses?limit=250&page=1`
`/v2/orders/taxes?limit=250&page=1`
`/v2/orders/shipments?limit=250&page=1`
`/v2/orders/messages?limit=250&page=1`
`/v2/orders/coupons?limit=250&page=1`

Iterate on the page number as you do with the parent resource.  You will need to use the `order_id` property on these subresource objects to attach them to the orders.  

This will of course change the process you currently follow to pull order data as you need to be able to dynamically assign the subresource data across the parent resource objects.  It is pretty straightforward though if you are storing this data into a database or collecting it all in memory before writing to a file.

As mentioned by @bc-AlyssNoland , the future V3 Orders API will have mechanisms in place to reduce requests needed just like the V3 Catalog allows the inclusion of subresource variant data into the parent product request.  In the meantime though you should find this providing significant reduction of requests and time to backup Order data.

Let me know if you have any questions and thank you for reaching out!

**Comment by Lewiscowles1986** [comment]
That solves everything TBH as it lets me work faster.
