### ISSUE TITLE
Who can I talk to about getting a free sandbox account?

### ISSUE THREAD

**Issue by achadee** [bigcommerce/api#82]
I've tried contacting support multiple times, but no luck

store-hash: "l2rumclm2t"

**Comment by bookernath** [comment]
Hi @achadee,

BigCommerce Partners can receive a free sandbox store for development purposes. Please visit https://partners.bigcommerce.com to learn more and apply.

**Comment by achadee** [comment]
@bookernath It seems you have a bug when you create the trail store before the partner account. I managed to get it working by creating a second store under my partner account
