### ISSUE TITLE
Issue with categories parameter in getProduct calls

### ISSUE THREAD

**Issue by jeffhannes** [bigcommerce/api#87]
When using the categories parameter to search for products using the v3 api...

If a product appears in multiple categories, it is NOT included in the search results. For example, I have a product (ToyWiz id 162663) that appears in both category 7080 and category 6996. But when I do either of the following api calls, the product is not returned in the results:

/v3/catalog/products/?categories=6996
/v3/catalog/products/?categories=7080

**Comment by bookernath** [comment]
Hi @jeffhannes, you'll want to use ?categories:in=6996 in this case. Without :in, this filter will return products that are EXCLUSIVELY in the given categories.
