### ISSUE TITLE
://undefined/carts in document 

### ISSUE THREAD

**Issue by amolasentech** [bigcommerce/api#90]
### Expected behavior
we need to change URL here so developer can understand.
https://developer.bigcommerce.com/api/v3/openapi-v3.html?python#post-carts

### Actual behavior
import requests
headers = {
  'Content-Type': 'application/json',
  'Accept': 'application/json'
}

r = requests.post('://undefined/carts', params={

}, headers = headers)

print r.json()

### Steps to reproduce behavior

what excet url here : ://undefined/carts

**Comment by PreciselyAlyss** [comment]
@amolasentech this should now be resolved. Please reopen if you see the same issue arise.
