### ISSUE TITLE
API Road-map: Abandoned Cart Messages / Webhook

### ISSUE THREAD

**Issue by ransomcarroll** [bigcommerce/api#91]
We would like to see the Abandoned Cart feature of BigCommerce exposed to the API. This is a major milestone that is necessary to be able to completely extract the email system out of the BigCommerce backed. 

Abandoned cart provides the user the ability to setup how often to message someone and also WHAT message to send. This information being exposed to the API and perhaps an accompanied web-hook that fired to init the cycle (passes in the customers info) would be helpful.

LMK if you have questions on this. Creating this issue as per instructions via the trello board.

**Comment by PreciselyAlyss** [comment]
@ransomcarroll We currently have a cart API in early access. Webhooks are on the rodmap for it. 
You can view details of the early access API [here](https://developer.bigcommerce.com/api/v3/openapi-v3.html#cart).

**Comment by ransomcarroll** [comment]
I don't think these are the same thing though, however the cart API could be used to pass in the "cart_id" along with the abandoned cart webhook.

The feature I want exposed to the API is found here in the BigCommerce backoffice "/manage/marketing/abandoned-cart-notifications"

**Comment by pddigital** [comment]
Agreed. Not sure it's a webhook. Maybe.

If you have a headless site/app just using the API, the abandoned cart features are useless. There should be some kind of workflow to create abandoned carts through the API...

**Comment by bookernath** [comment]
@pddigital @ransomcarroll I'm happy to report that we've just rolled out a webhook for "cart abandoned" events! You can subscribe to it using our webhooks resource:

https://developer.bigcommerce.com/api/#create-a-hook

The relevant (new) event is `store/cart/abandoned`. We'll be updating our documentation over the next couple of days.

**Comment by pddigital** [comment]
Sounds cool,
Is this being used in conjunction with the carts API? Assuming workflow is... cart is created via API > after a period of time the abandoned carts webhook fires if the cart hasn't been fulfilled/deleted > hits endpoint and I send an email to the user...

**Comment by serroba** [comment]
@pddigital that's a correct assumption. Just not _only_ for carts created via API. Any cart created using any of the possible flows we support should trigger the same event once reach the point of abandonment. Once the feature is fully rolled out, we will be updating documentation also

**Comment by bookernath** [comment]
Yep you've got the general idea. This will use BigCommerce's "definition" of an abandoned cart which is the same combination of factors we take into account for our own abandoned cart email feature.

On that note, you can also disable any of the transactional emails BC sends now, which might help in your integration... https://support.bigcommerce.com/articles/Public/Customizing-Email-Templates/#toggle
