### ISSUE TITLE
Incorrect link in documentation

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/api#98]
If you go here:

https://developer.bigcommerce.com/api/v3/

And click on the "Using the V3 API" link, it brings you here:

https://developer.bigcommerce.com/api/v3/#using-the-v3-api

Both of these links are the same. It seems like something is setup incorrectly with this link. I'm trying to read about how to get started with V3, but I can't seem to access the page. It's just and endless loop back to the V3 homepage.

**Comment by xjake** [comment]
What is it that you are trying to learn?

**Comment by flyingL123** [comment]
Was trying to get an overview of the changes from v2 to v3. The link was fixed earlier today, so I'm all set now. Thanks for the follow up.
