### ISSUE TITLE
Wishlist through the REST API

### ISSUE THREAD

**Issue by pddigital** [bigcommerce/api#99]
Wishlist data doesn't seem to be exposed through the API customer endpoint - it would be nice if this were a feature.

I'm not using your account backend, I'm rolling my own on my headless BC site - so basically, I have to store this info somewhere else (my own SQL db) which isn't great.

**Comment by serroba** [comment]
I'd like to know your use case. We have been talking about some ideas on this space, and to have use cases can be helpful if we decide to proceed with our ideas.

How would you like to be able to interact with such API, how do you see the integration with storefront?

As I said, having in mind possible use cases may help us at the moment we decide what direction to take.

**Comment by jeffhannes** [comment]
Though not related to the original poster's needs, here's a use case...

We have a robust Buy List with over 20,000 items that we are willing to buy from customers. Being able to pull the wishlist data would be tremendously useful, because then we could see which items we need to be more aggressive about keeping in stock, as well as which out-of-stock items we need should acquire. We do use a third-party out of stock solution so that customers can get e-mails, but if someone already has the item on their wishlist and it sells out, we'll have no way of knowing they want it.

It would also be useful to be able to run reports on wishlist data to help us figure out which products we should target for promotions. If we have a large stock of a particular item and it's on many customers' wishlists, it could be a good indicator that we need to drop the price and/or reach out to those customers.

**Comment by pddigital** [comment]
Thanks Serroba,

Wish list lets customers keep track of favorited products - stored under their customer record - and also allows marketing to run email campaigns against it by pulling favorited "wish list" products from their record.

Basically, I'd like most functionality available to your themes available via the API as well for custom headless builds -- 
Because I'm not using your themes or your customer portal, I'm rolling my own...

Some things I can't use,
Abandoned cart,
Wish list,
Discount codes need to be manually calculated since the orders endpoint doesn't allow for discount code validation/redemption

Probably other things...
The rest API is great by the way otherwise we wouldn't have signed on with ya'll, but it would be nice to be able to use these features. Your larger customers are probably going to opt for headless builds in the future because of the flexibility/performance it provides.

Thanks,
Paul

**Comment by serroba** [comment]
thanks guys for the feedback.

@pddigital can you please clarify here:

> Basically, I'd like most functionality available to your themes available via the API as well for custom headless builds --
> Because I'm not using your themes or your customer portal, I'm rolling my own...

You have in mind JavaScript clients (still attached to the storefront flow, but you want to build JS client on top of it) or do you mean entirely headless? do you want the ability to access from an entirely separate application?

**Comment by serroba** [comment]
As a work around, while we don't have public APIs for wishlist, why do you think the cart API is not a good candidate to use instead?
If you are managing your own relationship outside, you could create a collection of carts attached to a given customer?

I know is not ideal, I am just trying to understand how the cart API is not good enough to fulfil the use case. In other words, I want to understand what things, in base of your use case, the current API is lacking features so we consider them once we work on them.

**Comment by isalcedo** [comment]
I'm really interested on this. My company whats a better way to review customers wishlist without the tedious of login as user one by one. This is on some roadmap? There's a way we can help?

**Comment by STARL0RDZ** [comment]
Thanks for the feedback Ignacio,

I like the idea of exporting wishlist data. Would you call our support team
and ask them to attach the Engineering Request CATALOG-1120 to your account?

Best regards,


Jake Smith jake.smith@bigcommerce.com
<https://app.grooveapp.com/url/9r7tgp5go09qypbo6mqya8/bWFpbHRvOmpha2Uuc21pdGhAYmlnY29tbWVyY2UuY29t>
& 512-893-7341
<https://app.grooveapp.com/url/9r7tgp5go09qypbo6mqya8/dGVsOig1MTIpJTIwODkzLTczNDE%3D>



------------------------------------------------------------
------------------------------------------------------------------------
*Manager of Premium Services: evan.peterson@bigcommerce.com
<https://app.grooveapp.com/url/9r7tgp5go09qypbo6mqya8/bWFpbHRvOmV2YW4ucGV0ZXJzb25AYmlnY29tbWVyY2UuY29t>
**If
you have feedback or questions about the onboarding service you've
received, please email Evan Peterson.*


On Thu, Dec 28, 2017 at 7:51 AM, Ignacio Salcedo <notifications@github.com
<https://app.grooveapp.com/url/9r7tgp5go09qypbo6mqya8/bWFpbHRvOm5vdGlmaWNhdGlvbnNAZ2l0aHViLmNvbQ%3D%3D>

**Comment by isalcedo** [comment]
I'm just the lead developer. What information will they need? Also, This is a test to tray Whislist implementation in the API?

**Comment by serroba** [comment]
@isalcedo we don't have yet a clear date, but we are looking into whishlist and possible exposing them as APIs.
At the moment, to understand use cases can be of good value when designing a solution.

**Comment by isalcedo** [comment]
I already talked with my superiors. So we will take a look on what @STARL0RDZ wrote and I can help you with what we need and how we suppose to do it, @serroba. Thanks a lot.

**Comment by tkpk** [comment]
@jake-bc I was just researching how to pull reports in bulk of customer wishlists vs. going into each customer one by one.  I'm inferring that feature isn't available either via the UI, nor API, but perhaps is the subject of Engineering Request CATALOG-1120.  Is that correct?  Thank you

**Comment by richardsteers** [comment]
This is an issue for me also & the use case is slightly different.

We develop & implement a Customer Experience platform for retail brands. Synchronisation of a Customers Wish List(s) & their content between a brands App, in store Clienteling screens and eCommerce store is critical to modern day CX.

**Comment by serroba** [comment]
@richardsteers that's interesting. Could you please elaborate a bit more?

How would you describe your use case? What things would you like us to provide in order to enable your use case?

**Comment by richardsteers** [comment]
Sure @serroba - to create the best buying experience for a Customer with this type of function we enable them to create multiple wish lists which they can edit in any channel (eCom, App, Store, Social or Help Desk). Our product manages the CRUD of this data between each of the different platforms.

So a Customer might shop in store & staff can add products to the customers wish list from the register/change room/personal shopping experience via our Clienteling screen on POS or Table/mobile. The customer says "I like this item but I cant afford it right now", which enables the service rep to say "would you like me to add it to your wish list so you can quickly find it in future or receive notifications if it gets marked down?". 

From there they can see the product in the web & app views + we can then retarget with Com's or other display marketing chanels.

Or a Customer might LIKE an Instagram post featuring product(s) - if configured our platform can automatically add that product(s) to their wish list.

We only have to update the eCom wish list (as our data is populating the App, Store & Help Desk views). We do this currently with SalesForce Commerce Cloud and we are building Shopify Plus app which will also achieve this.

We have a current BigCommerce retail brand that is about to be onboarded and wants this functionality for their brand also.

**Comment by serroba** [comment]
Hey @richardsteers @pddigital @jeffhannes @isalcedo https://medium.com/bigcommerce-developer-blog/wishlist-api-new-targeted-marketing-capabilities-now-on-bigcommerce-6fe324363141

Please let us know what do you think

**Comment by bookernath** [comment]
Docs are here: https://developer.bigcommerce.com/api-reference/customer-subscribers/wishlist-api/wishlists/wishlistsget

Closing this issue as it's been resolved, but feedback is always welcome.
